/**
 * @brief No error.
 */
X(CAM_ERR_NONE)
/**
 * @brief Success.
 */
X(CAM_ERR_SUCCESS)
/**
 * @brief Failed to allocate memory.
 */
X(CAM_ERR_MEM_ALLOC)
/**
 * @brief Environment variable does not exist.
 */
X(CAM_ERR_NO_ENV_VAR)
/**
 * @brief A null pointer appeared in a non-nullable context.
 */
X(CAM_ERR_NULL_PTR)
/**
 * @brief Operation not permitted.
 */
X(CAM_ERR_OP_NOT_PERM)
/**
 * @brief File does not exist.
 */
X(CAM_ERR_NO_FILE)
/**
 * @brief Process does not exist.
 */
X(CAM_ERR_NO_PROC)
/**
 * @brief Interrupted system call.
 */
X(CAM_ERR_INTR_SYS_CALL)
/**
 * @brief I/O error.
 */
X(CAM_ERR_IO)
/**
 * @brief No device.
 */
X(CAM_ERR_NO_DEV)
/**
 * @brief Too many arguments.
 */
X(CAM_ERR_TOO_MANY_ARGS)
/**
 * @brief Permission denied.
 */
X(CAM_ERR_PERM_DENIED)
/**
 * @brief Invalid argument.
 */
X(CAM_ERR_INV_ARG)
/**
 * @brief Tried to access read-only sector.
 */
X(CAM_ERR_READ_ONLY)
/**
 * @brief File too large.
 */
X(CAM_ERR_FILE_TOO_LARGE)
/**
 * @brief Out of range.
 */
X(CAM_ERR_RANGE)
